#服务器端口
#server:
#  port: 1211
spring:
  application:
    #当前客户端实例名
    name: spring-cloud-user-service-consumer
eureka:
  client:
    service-url:
      #连接到的eureka服务器的URL
      defaultZone: http://server1:1111/eureka,http://server2:1112/eureka
    # 表示是否注册自身到eureka服务器
    #register-with-eureka: true
    # 是否从eureka上获取注册信息
    #fetch-registry: true
    instance:
      prefer-ip-address:true
